name: Process Debian Artifacts

on: 
  repository_dispatch:
    types: [deb]

jobs:
  Test-ISM-Plugin:
    needs: [sign-deb-artifacts]
    runs-on: [ubuntu-16.04]
    steps:
      - uses: actions/checkout@v1

      - uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: v1.8.0.0

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Debian Staging Distrubution
        run: |
          cd elasticsearch/linux_distributions
          es_version=`../bin/version-info --es`
          echo $es_version
          cd $GITHUB_WORKSPACE
          pwd
          sleep 20
          sudo sysctl -w vm.max_map_count=262144

          sudo add-apt-repository -y ppa:openjdk-r/ppa
          sudo apt update -y
          sudo apt install -y openjdk-11-jdk
          sudo sudo apt install -y net-tools

          wget -qO - https://d3g5vo6xdbdb9a.cloudfront.net/GPG-KEY-opendistroforelasticsearch | sudo apt-key add -
          echo "deb https://d3g5vo6xdbdb9a.cloudfront.net/staging/apt stable main" | sudo tee -a /etc/apt/sources.list.d/opendistroforelasticsearch.list

          wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-$es_version-amd64.deb
          sudo dpkg -i elasticsearch-oss-$es_version-amd64.deb

          sudo apt-get -y update
          sudo apt install -y opendistroforelasticsearch
          sudo mkdir repo
          sudo chmod 777 repo
          sudo chmod 777 /etc/elasticsearch/elasticsearch.yml
          sudo /usr/share/elasticsearch/bin/elasticsearch-plugin remove opendistro_security
          sudo sed -i '/path.logs/a path.repo: ["/$GITHUB_WORKSPACE/repo"]' /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^opendistro_security/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /CN=kirk/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^node.max_local_storage_nodes/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^cluster.routing.allocation.disk.threshold_enabled/d /etc/elasticsearch/elasticsearch.yml

          sudo /etc/init.d/elasticsearch start

          sleep 30
          cd index-management   
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200 -Dtests.clustername=es-integrationtest
          