name: IT for RPM

on:
#   schedule:
#     - cron: '0 10 * * *'
  repository_dispatch:
    types: [build-it]
  
jobs:
  Test-ISM-Plugin:
    name: Test ISM Plugin
    runs-on: ubuntu-latest
    container: 
      image: amazonlinux
      options: "-it --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --entrypoint /usr/sbin/init"
    steps:
      - uses: actions/checkout@v1

      - name: Checking out ISM repo
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: master

      - name: Running test
        run: |
          yum install systemd -y
          curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
          yum install java-1.8.0-openjdk-devel -y
          echo `file /etc/alternatives/java`
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.amzn2.0.1.x86_64/jre/bin/java
          echo $JAVA_HOME

