name: IT for RPM

on:
  repository_dispatch:
    types: [build-it]
  
jobs:
  Test-ISM-Plugin:
    name: Test ISM Plugin
    runs-on: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v1

      - name: Checking out ISM repo
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/index-management
          ref: opendistro-1.7

      - name: IT for ISM
        run: |
          sudo curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
          cd /opt
          sudo yum install wget tar -y
          sudo wget https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz
          sudo tar -xvf openjdk-13_linux-x64_bin.tar.gz
          export JAVA_HOME=/opt/jdk-13/
          export PATH=$PATH:/opt/jdk-13/bin
          sudo yum install unzip -y
          sudo yum install opendistroforelasticsearch-1.7.0 -y
          sudo chmod 777 /etc/elasticsearch/elasticsearch.yml     
          sudo sed -i /^opendistro_security/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /CN=kirk/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^node.max_local_storage_nodes/d /etc/elasticsearch/elasticsearch.yml
          sudo sed -i /^cluster.routing.allocation.disk.threshold_enabled/d /etc/elasticsearch/elasticsearch.yml
          sudo systemctl start elasticsearch.service
          sleep 30
          cd $GITHUB_WORKSPACE/../index-management
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200
  
  Test-Alerting-Plugin:
    name: Test Alerting Plugin
    runs: [self-hosted, Linux, X64]
    steps:
      - uses: actions/checkout@v1

      - name: Checking out Alerting repo
        uses: actions/checkout@v1
        with:
          repository: opendistro-for-elasticsearch/alerting
          ref: opendistro-1.7

      - name: IT for alerting
        run: |
          sudo systemctl status elasticsearch.service
          cd $GITHUB_WORKSPACE/../alerting
          ./gradlew integTest -Dtests.rest.cluster=localhost:9200 -Dtests.cluster=localhost:9200

