name: Build Windows Exe using tar artifacts

on:
  push:
    branches:
      - "test"

jobs:

  Test-Kibana-Notebooks-NoSec:
    runs-on: windows-latest
    name: Test-Kibana-Notebooks-NoSec
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Install yq
        run: .github/workflows/wget.ps1

      - name: Retrieve plugin tags
        run: |
          echo "p_tag_kib_nb=$(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/kibana-notebooks)" >> $GITHUB_ENV
          echo "es_version=$(release-tools/scripts/version-info.sh --es)" >> $GITHUB_ENV
          echo ${{env.es_version}}
      - name: Checkout Kibana
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: ${{env.es_version}}
          token: ${{ secrets.TOKEN }}
          path: kibana