name: Build Windows Exe using tar artifacts

on:
  push:
    branches:
      - "test"

jobs:
  Set-Env:
    runs-on: ubuntu-latest
    name: Set-Env
    env:
      es_version: $(release-tools/scripts/version-info.sh --es)
      p_tag_kib_nb: $(release-tools/scripts/plugin_tag.sh opendistro-for-elasticsearch/kibana-notebooks)
    steps:
      - uses: actions/checkout@v1

  Test-Kibana-Notebooks-NoSec:
    runs-on: windows-latest
    name: Test-Kibana-Notebooks-NoSec
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: ${{job.Set-Env.env.es_version}}
          token: ${{ secrets.TOKEN }}
          path: kibana