name: Build Windows Exe using tar artifacts

on:
  push:
    branches:
      - "test"

jobs:
  Set-Env:
    runs-on: ubuntu-latest
    name: Set-Env
    steps:
      - uses: actions/checkout@v1
      - name: Required packages
        run: release-tools/scripts/required_packages.sh
      - name: Set env
        env:
          es_version: release-tools/scripts/version-info.sh --es
      - name: Get env
        run: echo ${{env.es_version}}

  Test-Kibana-Notebooks-NoSec:
    needs: Set-Env
    runs-on: windows-latest
    name: Test-Kibana-Notebooks-NoSec
    strategy:
      fail-fast: false
      matrix:
        java: [14]
    steps:
      - uses: actions/checkout@v1

      - name: Checkout Kibana
        uses: actions/checkout@v2
        with:
          repository: opendistro-for-elasticsearch/kibana-oss
          ref: ${{job.Set-Env.env.es_version}}
          token: ${{ secrets.TOKEN }}
          path: kibana